name: dlatte_l2
target: models.model_discrete_latte.Latte_L_2
params:
  num_classes: ${data.num_classes}
  vocab_size: ${tokenizer.vocab_size}
  time_cond: ${dynamic.time_cond}
  input_size: ${tokenizer.latent_size}
  num_frames: ${data.video_frames}